version: "3.8"
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "neo4j/neo4jpassword"
    ports: ["7474:7474", "7687:7687"]
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  neo4j_data:
  minio_data:
